package com.saiy.models;

import java.math.BigDecimal;
import java.util.Date;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_id
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private Integer usersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_no
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_name
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_role
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private Integer usersRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_pass
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_tuijianren
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private Integer usersTuijianren;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_parentId
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private Integer usersParentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_yeji
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private BigDecimal usersYeji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_headimgurl
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersHeadimgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_age
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private Integer usersAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_sex
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_phone
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_email
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_idcard
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersIdcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_bankname
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersBankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_bankcard
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersBankcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_status
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_qq
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_shengfen
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersShengfen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_integral
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private BigDecimal usersIntegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_money
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private BigDecimal usersMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_jiangjin
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private BigDecimal usersJiangjin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_chongxiao
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private BigDecimal usersChongxiao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_jifen
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private BigDecimal usersJifen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_datetime
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private Date usersDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_baodanname
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersBaodanname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_youbian
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersYoubian;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_bankaddress
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersBankaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_minyeji
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private BigDecimal usersMinyeji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_chongzhi
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private BigDecimal usersChongzhi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_zuihouyeji
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private BigDecimal usersZuihouyeji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_shenhedate
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private Date usersShenhedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_getpassstr
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersGetpassstr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_getpassdate
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private Date usersGetpassdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_isbaodan
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersIsbaodan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_openid
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersOpenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_sendmsg
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private Boolean usersSendmsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_zhenshiname
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersZhenshiname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_ishuiyuan
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private Boolean usersIshuiyuan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_bankshengfen
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersBankshengfen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_bankcity
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersBankcity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_Qrcode
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String usersQrcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.users_createdate
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private Date usersCreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.default1
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String default1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.default2
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String default2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.default3
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String default3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.default4
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String default4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.default5
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private Boolean default5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.default6
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private Boolean default6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.default7
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private String default7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.default8
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private BigDecimal default8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.default9
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private BigDecimal default9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.default10
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    private BigDecimal default10;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_id
     *
     * @return the value of users.users_id
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public Integer getUsersId() {
        return usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_id
     *
     * @param usersId the value for users.users_id
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_no
     *
     * @return the value of users.users_no
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersNo() {
        return usersNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_no
     *
     * @param usersNo the value for users.users_no
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersNo(String usersNo) {
        this.usersNo = usersNo == null ? null : usersNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_name
     *
     * @return the value of users.users_name
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersName() {
        return usersName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_name
     *
     * @param usersName the value for users.users_name
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersName(String usersName) {
        this.usersName = usersName == null ? null : usersName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_role
     *
     * @return the value of users.users_role
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public Integer getUsersRole() {
        return usersRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_role
     *
     * @param usersRole the value for users.users_role
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersRole(Integer usersRole) {
        this.usersRole = usersRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_pass
     *
     * @return the value of users.users_pass
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersPass() {
        return usersPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_pass
     *
     * @param usersPass the value for users.users_pass
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersPass(String usersPass) {
        this.usersPass = usersPass == null ? null : usersPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_tuijianren
     *
     * @return the value of users.users_tuijianren
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public Integer getUsersTuijianren() {
        return usersTuijianren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_tuijianren
     *
     * @param usersTuijianren the value for users.users_tuijianren
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersTuijianren(Integer usersTuijianren) {
        this.usersTuijianren = usersTuijianren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_parentId
     *
     * @return the value of users.users_parentId
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public Integer getUsersParentid() {
        return usersParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_parentId
     *
     * @param usersParentid the value for users.users_parentId
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersParentid(Integer usersParentid) {
        this.usersParentid = usersParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_yeji
     *
     * @return the value of users.users_yeji
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public BigDecimal getUsersYeji() {
        return usersYeji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_yeji
     *
     * @param usersYeji the value for users.users_yeji
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersYeji(BigDecimal usersYeji) {
        this.usersYeji = usersYeji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_headimgurl
     *
     * @return the value of users.users_headimgurl
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersHeadimgurl() {
        return usersHeadimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_headimgurl
     *
     * @param usersHeadimgurl the value for users.users_headimgurl
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersHeadimgurl(String usersHeadimgurl) {
        this.usersHeadimgurl = usersHeadimgurl == null ? null : usersHeadimgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_age
     *
     * @return the value of users.users_age
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public Integer getUsersAge() {
        return usersAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_age
     *
     * @param usersAge the value for users.users_age
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersAge(Integer usersAge) {
        this.usersAge = usersAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_sex
     *
     * @return the value of users.users_sex
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersSex() {
        return usersSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_sex
     *
     * @param usersSex the value for users.users_sex
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersSex(String usersSex) {
        this.usersSex = usersSex == null ? null : usersSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_phone
     *
     * @return the value of users.users_phone
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersPhone() {
        return usersPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_phone
     *
     * @param usersPhone the value for users.users_phone
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersPhone(String usersPhone) {
        this.usersPhone = usersPhone == null ? null : usersPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_email
     *
     * @return the value of users.users_email
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersEmail() {
        return usersEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_email
     *
     * @param usersEmail the value for users.users_email
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersEmail(String usersEmail) {
        this.usersEmail = usersEmail == null ? null : usersEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_idcard
     *
     * @return the value of users.users_idcard
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersIdcard() {
        return usersIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_idcard
     *
     * @param usersIdcard the value for users.users_idcard
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersIdcard(String usersIdcard) {
        this.usersIdcard = usersIdcard == null ? null : usersIdcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_bankname
     *
     * @return the value of users.users_bankname
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersBankname() {
        return usersBankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_bankname
     *
     * @param usersBankname the value for users.users_bankname
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersBankname(String usersBankname) {
        this.usersBankname = usersBankname == null ? null : usersBankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_bankcard
     *
     * @return the value of users.users_bankcard
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersBankcard() {
        return usersBankcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_bankcard
     *
     * @param usersBankcard the value for users.users_bankcard
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersBankcard(String usersBankcard) {
        this.usersBankcard = usersBankcard == null ? null : usersBankcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_status
     *
     * @return the value of users.users_status
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersStatus() {
        return usersStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_status
     *
     * @param usersStatus the value for users.users_status
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersStatus(String usersStatus) {
        this.usersStatus = usersStatus == null ? null : usersStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_qq
     *
     * @return the value of users.users_qq
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersQq() {
        return usersQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_qq
     *
     * @param usersQq the value for users.users_qq
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersQq(String usersQq) {
        this.usersQq = usersQq == null ? null : usersQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_shengfen
     *
     * @return the value of users.users_shengfen
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersShengfen() {
        return usersShengfen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_shengfen
     *
     * @param usersShengfen the value for users.users_shengfen
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersShengfen(String usersShengfen) {
        this.usersShengfen = usersShengfen == null ? null : usersShengfen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_integral
     *
     * @return the value of users.users_integral
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public BigDecimal getUsersIntegral() {
        return usersIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_integral
     *
     * @param usersIntegral the value for users.users_integral
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersIntegral(BigDecimal usersIntegral) {
        this.usersIntegral = usersIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_money
     *
     * @return the value of users.users_money
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public BigDecimal getUsersMoney() {
        return usersMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_money
     *
     * @param usersMoney the value for users.users_money
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersMoney(BigDecimal usersMoney) {
        this.usersMoney = usersMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_jiangjin
     *
     * @return the value of users.users_jiangjin
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public BigDecimal getUsersJiangjin() {
        return usersJiangjin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_jiangjin
     *
     * @param usersJiangjin the value for users.users_jiangjin
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersJiangjin(BigDecimal usersJiangjin) {
        this.usersJiangjin = usersJiangjin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_chongxiao
     *
     * @return the value of users.users_chongxiao
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public BigDecimal getUsersChongxiao() {
        return usersChongxiao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_chongxiao
     *
     * @param usersChongxiao the value for users.users_chongxiao
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersChongxiao(BigDecimal usersChongxiao) {
        this.usersChongxiao = usersChongxiao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_jifen
     *
     * @return the value of users.users_jifen
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public BigDecimal getUsersJifen() {
        return usersJifen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_jifen
     *
     * @param usersJifen the value for users.users_jifen
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersJifen(BigDecimal usersJifen) {
        this.usersJifen = usersJifen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_datetime
     *
     * @return the value of users.users_datetime
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public Date getUsersDatetime() {
        return usersDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_datetime
     *
     * @param usersDatetime the value for users.users_datetime
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersDatetime(Date usersDatetime) {
        this.usersDatetime = usersDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_baodanname
     *
     * @return the value of users.users_baodanname
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersBaodanname() {
        return usersBaodanname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_baodanname
     *
     * @param usersBaodanname the value for users.users_baodanname
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersBaodanname(String usersBaodanname) {
        this.usersBaodanname = usersBaodanname == null ? null : usersBaodanname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_youbian
     *
     * @return the value of users.users_youbian
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersYoubian() {
        return usersYoubian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_youbian
     *
     * @param usersYoubian the value for users.users_youbian
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersYoubian(String usersYoubian) {
        this.usersYoubian = usersYoubian == null ? null : usersYoubian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_bankaddress
     *
     * @return the value of users.users_bankaddress
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersBankaddress() {
        return usersBankaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_bankaddress
     *
     * @param usersBankaddress the value for users.users_bankaddress
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersBankaddress(String usersBankaddress) {
        this.usersBankaddress = usersBankaddress == null ? null : usersBankaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_minyeji
     *
     * @return the value of users.users_minyeji
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public BigDecimal getUsersMinyeji() {
        return usersMinyeji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_minyeji
     *
     * @param usersMinyeji the value for users.users_minyeji
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersMinyeji(BigDecimal usersMinyeji) {
        this.usersMinyeji = usersMinyeji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_chongzhi
     *
     * @return the value of users.users_chongzhi
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public BigDecimal getUsersChongzhi() {
        return usersChongzhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_chongzhi
     *
     * @param usersChongzhi the value for users.users_chongzhi
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersChongzhi(BigDecimal usersChongzhi) {
        this.usersChongzhi = usersChongzhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_zuihouyeji
     *
     * @return the value of users.users_zuihouyeji
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public BigDecimal getUsersZuihouyeji() {
        return usersZuihouyeji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_zuihouyeji
     *
     * @param usersZuihouyeji the value for users.users_zuihouyeji
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersZuihouyeji(BigDecimal usersZuihouyeji) {
        this.usersZuihouyeji = usersZuihouyeji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_shenhedate
     *
     * @return the value of users.users_shenhedate
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public Date getUsersShenhedate() {
        return usersShenhedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_shenhedate
     *
     * @param usersShenhedate the value for users.users_shenhedate
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersShenhedate(Date usersShenhedate) {
        this.usersShenhedate = usersShenhedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_getpassstr
     *
     * @return the value of users.users_getpassstr
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersGetpassstr() {
        return usersGetpassstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_getpassstr
     *
     * @param usersGetpassstr the value for users.users_getpassstr
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersGetpassstr(String usersGetpassstr) {
        this.usersGetpassstr = usersGetpassstr == null ? null : usersGetpassstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_getpassdate
     *
     * @return the value of users.users_getpassdate
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public Date getUsersGetpassdate() {
        return usersGetpassdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_getpassdate
     *
     * @param usersGetpassdate the value for users.users_getpassdate
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersGetpassdate(Date usersGetpassdate) {
        this.usersGetpassdate = usersGetpassdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_isbaodan
     *
     * @return the value of users.users_isbaodan
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersIsbaodan() {
        return usersIsbaodan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_isbaodan
     *
     * @param usersIsbaodan the value for users.users_isbaodan
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersIsbaodan(String usersIsbaodan) {
        this.usersIsbaodan = usersIsbaodan == null ? null : usersIsbaodan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_openid
     *
     * @return the value of users.users_openid
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersOpenid() {
        return usersOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_openid
     *
     * @param usersOpenid the value for users.users_openid
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersOpenid(String usersOpenid) {
        this.usersOpenid = usersOpenid == null ? null : usersOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_sendmsg
     *
     * @return the value of users.users_sendmsg
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public Boolean getUsersSendmsg() {
        return usersSendmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_sendmsg
     *
     * @param usersSendmsg the value for users.users_sendmsg
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersSendmsg(Boolean usersSendmsg) {
        this.usersSendmsg = usersSendmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_zhenshiname
     *
     * @return the value of users.users_zhenshiname
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersZhenshiname() {
        return usersZhenshiname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_zhenshiname
     *
     * @param usersZhenshiname the value for users.users_zhenshiname
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersZhenshiname(String usersZhenshiname) {
        this.usersZhenshiname = usersZhenshiname == null ? null : usersZhenshiname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_ishuiyuan
     *
     * @return the value of users.users_ishuiyuan
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public Boolean getUsersIshuiyuan() {
        return usersIshuiyuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_ishuiyuan
     *
     * @param usersIshuiyuan the value for users.users_ishuiyuan
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersIshuiyuan(Boolean usersIshuiyuan) {
        this.usersIshuiyuan = usersIshuiyuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_bankshengfen
     *
     * @return the value of users.users_bankshengfen
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersBankshengfen() {
        return usersBankshengfen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_bankshengfen
     *
     * @param usersBankshengfen the value for users.users_bankshengfen
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersBankshengfen(String usersBankshengfen) {
        this.usersBankshengfen = usersBankshengfen == null ? null : usersBankshengfen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_bankcity
     *
     * @return the value of users.users_bankcity
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersBankcity() {
        return usersBankcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_bankcity
     *
     * @param usersBankcity the value for users.users_bankcity
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersBankcity(String usersBankcity) {
        this.usersBankcity = usersBankcity == null ? null : usersBankcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_Qrcode
     *
     * @return the value of users.users_Qrcode
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getUsersQrcode() {
        return usersQrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_Qrcode
     *
     * @param usersQrcode the value for users.users_Qrcode
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersQrcode(String usersQrcode) {
        this.usersQrcode = usersQrcode == null ? null : usersQrcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.users_createdate
     *
     * @return the value of users.users_createdate
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public Date getUsersCreatedate() {
        return usersCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.users_createdate
     *
     * @param usersCreatedate the value for users.users_createdate
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setUsersCreatedate(Date usersCreatedate) {
        this.usersCreatedate = usersCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.default1
     *
     * @return the value of users.default1
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getDefault1() {
        return default1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.default1
     *
     * @param default1 the value for users.default1
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setDefault1(String default1) {
        this.default1 = default1 == null ? null : default1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.default2
     *
     * @return the value of users.default2
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getDefault2() {
        return default2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.default2
     *
     * @param default2 the value for users.default2
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setDefault2(String default2) {
        this.default2 = default2 == null ? null : default2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.default3
     *
     * @return the value of users.default3
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getDefault3() {
        return default3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.default3
     *
     * @param default3 the value for users.default3
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setDefault3(String default3) {
        this.default3 = default3 == null ? null : default3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.default4
     *
     * @return the value of users.default4
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getDefault4() {
        return default4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.default4
     *
     * @param default4 the value for users.default4
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setDefault4(String default4) {
        this.default4 = default4 == null ? null : default4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.default5
     *
     * @return the value of users.default5
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public Boolean getDefault5() {
        return default5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.default5
     *
     * @param default5 the value for users.default5
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setDefault5(Boolean default5) {
        this.default5 = default5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.default6
     *
     * @return the value of users.default6
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public Boolean getDefault6() {
        return default6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.default6
     *
     * @param default6 the value for users.default6
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setDefault6(Boolean default6) {
        this.default6 = default6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.default7
     *
     * @return the value of users.default7
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public String getDefault7() {
        return default7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.default7
     *
     * @param default7 the value for users.default7
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setDefault7(String default7) {
        this.default7 = default7 == null ? null : default7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.default8
     *
     * @return the value of users.default8
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public BigDecimal getDefault8() {
        return default8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.default8
     *
     * @param default8 the value for users.default8
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setDefault8(BigDecimal default8) {
        this.default8 = default8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.default9
     *
     * @return the value of users.default9
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public BigDecimal getDefault9() {
        return default9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.default9
     *
     * @param default9 the value for users.default9
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setDefault9(BigDecimal default9) {
        this.default9 = default9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.default10
     *
     * @return the value of users.default10
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public BigDecimal getDefault10() {
        return default10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.default10
     *
     * @param default10 the value for users.default10
     *
     * @mbggenerated Fri Dec 30 15:34:29 CST 2016
     */
    public void setDefault10(BigDecimal default10) {
        this.default10 = default10;
    }
}